apiVersion: v1
kind: Service
metadata:
  labels:
    app: helm-engine
  annotations: {}
  name: helm-engine
  namespace: uca-paas-eams
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: helm-engine
  type: ClusterIP